### PR TITLE
fix: enable setting layout_strategy that isnt horizontal or cursor

### LINKED ISSUE #28: [Bug]: Telescope layout_config conflict, cannot use vertical layout strategy
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read [the docs, and in particular the FAQ](https://github.com/chrisgrieser/nvim-scissors#table-of-contents).
- [X] The problem is related to creating or editing snippets. (Expanding and using snippet is the responsibility of the snippet engine plugin, such as Luasnip or nvim-snippets.)

### Bug Description

Since the final telescope config uses a [tbl_deep_extend](https://github.com/chrisgrieser/nvim-scissors/blob/d65cde840766a7ccaf0d59326ad34c81f5ed40f7/lua/scissors/config.lua#L60) of `defaultConfig`, it seems impossible to set layout_strategy to `vertical`, [since setting](https://github.com/chrisgrieser/nvim-scissors//blob/d65cde840766a7ccaf0d59326ad34c81f5ed40f7/lua/scissors/config.lua#L33) `preview_width` when using a `vertical` strategy causes an error.

Is there a way to unset `preview_width`

### Relevant Screenshot

_No response_

### To Reproduce

Set `opts.telescope.opts.layout_strategy = "vertical"`.

You should get an error like
```
ScissorsEditSnippet Unsupported layout_config key for the vertical strategy: preview_width
```

### neovim version

```Text
0.11.0-dev
```

### PR DESCRIPTION
**Pull request by kraftnix**
Removes incompatible `preview_width` option from telescope options when using an incompatible `layout_strategy`.

Closes #28.

## Checklist
- [x] Used only camelCase variable names.
- [x] If functionality is added or modified, also made respective changes to the
  `README.md` (the `.txt` file is auto-generated and does not need to be modified).

### CODE REVIEW

File: lua/scissors/config.lua [hunk 1]
```diff
@@ -59,6 +59,12 @@ M.config = defaultConfig -- in case user does not call `setup`
 function M.setupPlugin(userConfig)
 	M.config = vim.tbl_deep_extend("force", defaultConfig, userConfig or {})
 
+	-- preview_width is only supported by `horizontal` and `cursor` strategies
+	local strategy = M.config.telescope.opts.layout_strategy
+	if not (strategy == "horizontal" or strategy == "cursor") then
```
Comment (chrisgrieser) [inline lua/scissors/config.lua:64]: Better to use 2x `~=` here

**Review by chrisgrieser — CHANGES_REQUESTED** [review]
